# Generated by Django 4.1.2 on 2022-11-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
