# Generated by Django 4.1.2 on 2022-12-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_product_exhibits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibits',
            name='price',
        ),
        migrations.RemoveField(
            model_name='exhibits',
            name='quatity',
        ),
    ]
